# Basic configuration
language: java
jdk: openjdk8

script: ./travis.script.sh

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.gradle/wrapper
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
